export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"

export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORY = "GET_CATEGORY"

export const GET_ERRORS = "GET_ERRORS"

export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET"
export const GET_NUMBERS_BASKET = "GET_NUMBERS_BASKET"
export const GET_PRODUCTSCART = "GET_PRODUCTSCART"

export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
export const CLEAR_PRODUCT = "CLEAR_PRODUCT"

export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const GET_CUSTOMER = "GET_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"

export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL"
export const CREATE_ORDER_ITEMS = "CREATE_ORDER_ITEMS"